sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 471520
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tK9nQGHxPzfrRxur227
    access-key-secret: S3P5N1UDuCavPy8KluVSIo5iGep1Hx
    bucket-name: inno-takeout
  redis:
    host: localhost
    port: 6379
    password: 471520
    database: 0
  wechat:
    appid: wx3715ac2ef34b87d2
    secret: 52ece487292b3aebd07cc3e2fc2d6d8a
